

API_URL = 'http://api.bitcoke.com/'
TRADE_API_URL = 'http://api.bitcoke.com/trade/'


#Instrument
SYMBOL_XBTCUSD = 'XBTCUSD'
SYMBOL_XETHUSD = 'XETHUSD'
SYMBOL_XEOSWUSD = 'XEOSUSD'
SYMBOL_XLTCUSD = 'XLTCUSD'
SYMBOL_XBCHUSD = 'XBCHUSD'

#Index
SYMBOL_BTCUSD = 'BTCUSD'
SYMBOL_ETHUSD = 'ETHUSD'
SYMBOL_EOSWUSD = 'EOSUSD'
SYMBOL_LTCUSD = 'LTCUSD'
SYMBOL_BCHUSD = 'BCHUSD'

#currency
CURRENCY_BTC = 'BTC'
CURRENCY_EOS = 'EOS'
CURRENCY_ETH = 'ETH'
CURRENCY_USDT = 'USDT'

#Type of order price
ORDER_TYPE_LIMIT = 'Limit'
ORDER_TYPE_MARKET = 'Market'

#Order side
SIDE_BUY = 'Buy'
SIDE_SELL = 'Sell'

#Type of advanced order
TIF_GOOD_TILL_CANCEL = 'GOOD_TILL_CANCEL'
TIF_IMMEDIATE_OR_CANCEL = 'IMMEDIATE_OR_CANCEL'
TIF_FILL_OR_KILL = 'FILL_OR_KILL'
TIF_QUEUE_OR_CANCEL = 'QUEUE_OR_CANCEL'

#Trigger type of price for conditional order
TIGGER_TYPE_LAST = "LAST"
TIGGER_TYPE_INDEX = "INDEX"

#Position side
SIDE_LONG = 'Long'
SIDE_SHORT = 'Short'

#K line Type
K_LINE_TYPE_1M = '1M'
K_LINE_TYPE_3M = '3M'
K_LINE_TYPE_5M = '5M'
K_LINE_TYPE_10M = '10M'
K_LINE_TYPE_15M = '15M'
K_LINE_TYPE_30M = '30M'
K_LINE_TYPE_1H = '1H'
K_LINE_TYPE_2H = '2H'
K_LINE_TYPE_4H = '4H'
K_LINE_TYPE_6H = '6H'
K_LINE_TYPE_8H = '8H'
K_LINE_TYPE_12H = '12H'
K_LINE_TYPE_D = 'D'
K_LINE_TYPE_W = 'W'
K_LINE_TYPE_MTH = 'MTH'


